server:
  port: 8087
spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/test1?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      initialSize: 1
      minIdle: 1
      maxActive: 10
      maxWait: 10000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 1
      testWhileIdle: true
      testOnBorrow: true
      testOnReturn: false
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      filters: stat
# ====================MybatisPlus====================
mybatis-plus:
# 如果是放在src/main/java目录下 classpath:/com/yourpackage/*/mapper/*Mapper.xml
# 如果是放在resource目录 classpath:/mapper/*Mapper.xml
  mapper-locations: classpath:mapping/*Mapper.xml,classpath*:mapping/**/**.xml
#实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.enesoon.business.*.entity
#打印sql
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    
# ====================pagehelper====================  
pagehelper: 
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  pageSizeZero: true
  params=count: countSql
