server:
  port: 9411
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka/
spring:
  application:
    name: zipkin-server
  zipkin:
    base-url: http://127.0.0.1:9411
management: 
  metrics: 
    web: 
      server: 
        auto-time-requests: false