server:
  port: 8082

spring:
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: D:/enesoon_tangwq/jar/config
          #search-locations: classpath:/shared
      label: master

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka/

